### ISSUE TITLE
1_plane driver obsolete?

### ISSUE THREAD

**Issue by th-otto** [freemint/fvdi#3]
It occurs to me that the 1_plane and 1_dummy directories are quite useless nowadays. The 1_plane drivers does not even compile from the makefile, it needs some special processing by the make.sh script. Similar for 1_dummy driver, which seems to be incomplete and does not even have a Makefile. Would be ok to just remove them?  monochrome modes are already handled by the bitplane driver.

**Comment by mfro0** [comment]
Wasn't sure if the bitplane driver would support TT high, but it 
obviously does as a quick test with hatari showed.

I would be o.k. with removing the 1_plane then. But beware, the bitplane 
driver uses 1_plane.inc from there.

Am 18.05.20 um 15:03 schrieb Thorsten Otto:
